# Run `travis lint` when changing this file to avoid breaking the build.

cache:
  directories:
    - $HOME/.m2

language: java

jdk: openjdk11

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

# Override default travis to use the maven wrapper; skip license on travis due to #1512
install: ./mvnw install -Dlicense.skip=true -Dmaven.javadoc.skip=true -B -V

script: ./travis/publish.sh
# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/e57478303f87ecd7bffc
    on_success: change
    on_failure: always

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "b/12qlIYpraAmiqQiiCUDGHrL7cmuPCPc3oSFiLlDiqetTxgG7M8tal0BRpHrP3UWHdNfF0aCzgQSzQ342xhRJsvPH6BahUXIhKBSxjq+iA2I0/bFphvFjmLuqU3vjT3F4kaomd4zwNaMflD4zI6/VRQDe5Y3BGN39biiM93vTMYGuzdLp0c8xFO4GpxA2IyX7DJpmHkf5umIQ7tCJVPRJUF1Kzo+PgM4JI+NuixrlqpF9Pnte/axEkK25UGpql4Ssl1DQEwXsE2ZU0Fn5rAOYiI2hqyTkQ/1Q5Yw4tOKDcjUQYefv1vHambNhIos3pvLhQzAQwdDp/Z2NZV3FhIDrFFIyaXmXo3PcbX/4I274NXO8dVj0lR5edbbq2Q2WTXb8S8LJbdA/4pkcvenwTXTUCWP9rqImXs8XwoxjcAc8lgVV8bPd6T6idNY2PYlhUDkzEPAMU2BZEYK2sSGS94lpAellxRYAbDcHWE7gircj6baWP8aoULilBGaVTMwGRpVksURhWZ6QRNQWpMcAMZXq2rcEEbL1L1mQFV0Y9WVk614m/8/i2DyXX5w6hXjAp7qobWK4CQg/DFx6lfUcGmYgE9sqVChgWDyUwMAXsmalUp7z5opiR1nBbwfetRC2xbFdsWGwCzR84bsXwNaM83Q99UdGm2HLUWMQTvRpiXG50="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "XTmslsGYBudNBKTTIkF5d3JI7j2ZxMMeOw2/L1U+AuMAE3GGy3hSFsjnrXQC+dhdOkNmVwrsoC6Fa9Hk2J+7pXUUec4aJWd/cy+NVkrU7EgylYNndWRpyIwpY0JvCiAdUEMCWXgp2DCyoxdyACB3c+9iAlVYuHS5ug2E/S/gwhAkXef6B7YZ4GjKjTKKT3iBf+0S9LxeQYJZOb//XReufdCLwwXnhw9CpGwqNJq2nh9JhgEtLFaWaEOqKdlgiMngXdWqglCmdKokt4NuxCpQlb0T3T/bbNZBoa/K95Y5kJZoRj+sCSqt8ajsFiJH7unnF5y0qT09GStDsxY480GagfE4gxPoyR91TOCBUw5m18B/36nqvd1l1R8qXqsjw6Eee+loZebRGphZ/sse0nOA0dStNDg+RudGN4mvoGq6CsrX8bikndtfbBb/YgCODGHahK1c3OYXnmrG/xZaRe5tHMCfv6ymyEbHU0IOBxtR6m4yFH4c0mktcZVL20Tt2C9miaeXS+9/NMqSo7sIlX+BLpxsHi/t+aYwlpNpQvPQnBh9hP4AuCuQGYgQsor1cZBb3XFDT9IoVrAEFqec0sfc5GiTF0jDcgP8ME5qCsUXFRfFOstWgLO5UhPWdhCnSL1+j3rWhMmI91Kc5B4AmL2BiYhl9lSkHUaZAeKCZuZdttQ="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "U8Xul+Mj5kTFfsNNV+jW/+CUPREku63k5w9R9OaVGtfHXf4ytxHoRL4LwUtVMzfB/TdHuiujBhUz4/zOvq8q+Ra2HJh83hqepg/7lH/aeb3XYMU1GHdts89GHOOaZcTzYaI3GxdxZVBYN9EplT06PQqMXUMZv55YDzFST2fbsaQ407MvzvdlGwygV8dA9PQtuUVKzc0WVklxkDYxpep9BThj3by2LRXkaeaZnQsypv9LUeAYXIsDvzSsTmAqn9/I6twT+ocErWGGUuFiMUcO1T6CKnNRi0rX4mvXsbF+7HUPZBPApExpbG7b85KAW9nL82T+mKJ1lKWnnLtzmMS4xcTbDFX/imeccCRiRNt1HdRHqRimDl/6EUzNABhtyHYQI/jB4jBppfB+4KYolcPj1Xci5M24Pv/zIWcwJosVrtOfnF1LAD835X1kqU45YJbFDyeK29K0UefXhGRYq1t9SDuX+WLgWb7HmE8olyj5hreCXHZx9LWoglJkURII9mXlOOfMz9MAoPF9rqDPxbfMfcr1x3m5u39ZXQ5W4znYKVBNWAu71kgxAnrQ8G/OgvUqdTgGty1meLe5DfNpaC5iy67NToAUjNeFjkAfo4Fz6SC7b83343CgG5YEmvlAQr6ZzY6IA89l0VCH/3MhYPJQ1esF6Kq6VywpU+nJiVsiz2Y="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "tbzQ9cRFbOJhnuFRJAGbx10DxyW3jH4ogbe5JNTx8VfdAmAplgV5g91OGE2PjFeIQAwroB+2DpNQ+t0UTylDLEDIPrS5QMWQiXMUI/LP4dGzSla2lNjl8dbbgXRkGMuCLZuunmOiFURgtmZLyPzX0ALJvC68TGg9WxA7FUZh1Z+lwUTB7e88UMwsgxqYGmDqVCJfBPC9REnK+MoQVGdlv6kj87cSPOx0WUETvDiHO4Z3E6MbgjORxF/9jGX2PuUwKbm0VDpxohN9SYD2bD6JQKJ6P8xIwC92xMbR6ndg1DQ20o9KRIqaCAk6aLpk0aKRcih+YlhZXYe2AfKhRmezEI6G6gljiRRKHESyJHtCgbheyfcKAbBAxmMmQmImRJK5+7QgOam0mKwKXeE4Pml7mNk68Pq5Kgt/eF8oYH9uHeYXE9AIYBmi2HSQsohBhgrHX9t3Zb/fahAc2XtOEvG7of46fV8Mqbhn7PfEwvVMx4+3dHOZlI2PEmOgC93E/CFIKps1hzbcU5Ki+vRjFtKOg36NpuM/ePaFMhLs06KKd1p1xLGysocs7k1eT9jyti514AO50z/QQpjw+eNOvl/NXyFSC/MtbDSYrtTDPwHCuMZpNI9nK2ozMap3UFac/jerg5oZ8Iu5oAU9hA7VewlGFsTSNJ/DjeL0rvPIhpfo99M="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "nEaT4J3F3s7ERpy3lW6g9KkrMgjX9vxzfc4KlUSq1PC+70n9w62zGsoFQJOjA9psBrKzkOik+7/lk4tLmIy+O2CDerbVypflWwyNEoIW+OD95gcjlZBJVxEp2/z55OQG4a0qivrpwiCMNrAAvqrWWYp7rjkpNxuvgqDKsDrCMlQltLf97ND5vIwAscqCWH1MZoPCEShIhsbHQa+EWaDR5EY3bXsGMaqPWTitUpBvHUhYJkeSmaW3cMxOAKYyxqApbhb4OnXAntjxYJ8ltjJ2nw+27erLOeMzhdxpt6srE+dO1Kh11vLJ+5u+bZdq3YttQ5BfPzOu6jVzSHlj3NovkyyIVOLgzM0JnNYulA8sExwr0ZM1vYq32cpmYYCu6hvXUeIga9gihXKFx6Xb0I7/3b9/d0XOeDhJw7+KJBvaCeu3NOP0Gle97Jwo2KZzU7xxFAkyLVa5o2lsDvXoOoyEQmyTVSW9jIR8CU08RS2gSy8IcaGW8etw+A+8Bjsq5Ly88yjUfoDEnKSU0zvdWhdv8/ZpF2ka5nApHXSSvrBZzDJGDshZlFC/tiVpfXk/1vtp4zYcQprrGb+XqgifS35HkNaqiv86IQQzb1WSaT4fX3rj4CZWejz6/N7SnDm0CXzdNGwbY88B27WtCBTnwotlBUyXHPlJIe+h3p7+RUQGaMw="

