# Run `travis lint` when changing this file to avoid breaking the build.

cache:
  directories:
    - $HOME/.m2

language: java

jdk: openjdk11

# Override default travis to use the maven wrapper; skip license on travis due to #1512
install: ./mvnw verify -Dlicense.skip=true -B
